//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppCreditas {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringTable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringTable() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppCreditas.StringTable", typeof(StringTable).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a App Creditas.
        /// </summary>
        internal static string App_Creditas {
            get {
                return ResourceManager.GetString("App_Creditas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a OK.
        /// </summary>
        internal static string Label_OK {
            get {
                return ResourceManager.GetString("Label_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User ou Password are incorrect, please try again!.
        /// </summary>
        internal static string Message_WrongLogin {
            get {
                return ResourceManager.GetString("Message_WrongLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Chat.
        /// </summary>
        internal static string Page_Chat {
            get {
                return ResourceManager.GetString("Page_Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Extract.
        /// </summary>
        internal static string Page_Extract {
            get {
                return ResourceManager.GetString("Page_Extract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Outbound.
        /// </summary>
        internal static string Page_Outbound {
            get {
                return ResourceManager.GetString("Page_Outbound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Simulator.
        /// </summary>
        internal static string Page_Simulator {
            get {
                return ResourceManager.GetString("Page_Simulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Login.
        /// </summary>
        internal static string TextLabel_Page_LoginView_Login {
            get {
                return ResourceManager.GetString("TextLabel_Page_LoginView_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Password.
        /// </summary>
        internal static string TextLabel_Page_LoginView_Password {
            get {
                return ResourceManager.GetString("TextLabel_Page_LoginView_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Go To Simulate.
        /// </summary>
        internal static string TextLabel_Page_LoginView_Simulate_Here {
            get {
                return ResourceManager.GetString("TextLabel_Page_LoginView_Simulate_Here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Username.
        /// </summary>
        internal static string TextLabel_Page_LoginView_User {
            get {
                return ResourceManager.GetString("TextLabel_Page_LoginView_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Car.
        /// </summary>
        internal static string TextLabel_Page_Simulator_Car {
            get {
                return ResourceManager.GetString("TextLabel_Page_Simulator_Car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a House.
        /// </summary>
        internal static string TextLabel_Page_Simulator_House {
            get {
                return ResourceManager.GetString("TextLabel_Page_Simulator_House", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a How much do you need?.
        /// </summary>
        internal static string TextLabel_Page_Simulator_How_Much {
            get {
                return ResourceManager.GetString("TextLabel_Page_Simulator_How_Much", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a What type of loan do you need?.
        /// </summary>
        internal static string TextLabel_Page_Simulator_What_Loan {
            get {
                return ResourceManager.GetString("TextLabel_Page_Simulator_What_Loan", resourceCulture);
            }
        }
    }
}
